#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     motors,         sensorI2CMuxController)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     liftTS,         sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftFrontMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftRearMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightRearMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     liftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     spinnerMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    goalHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    hopperTilt,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    highGoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    unusedS3C14,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    unusedS3C15,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    unusedS3C16,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickGame");
#define SONAR_DEBUG
#include "../includes.h"

task main()
{
	bool valid = false;
	initializeRobot();
	waitForStart();

	// Get the lift going
	StartTask(Lift);
	waitLiftReady();

	// Goal to side
	if(readSonarMax(5) > 130) {

		//Drive out to not hit wall
		driveToEncoder(AUTO_DRIVE_SPEED, 150);

		// Turn left, drive past the beacon, turn back
		driveToGyro(30, TURN_LEFT);
		driveToEncoder(AUTO_DRIVE_SPEED, 6250);
		driveToGyro(120, !TURN_LEFT);

		// Turn to IR alignment
		valid = driveToIR(-AUTO_DRIVE_SPEED, true, false, IR_MID);

	// Goal intermediate or ahead
	} else {
		// Drive ahead to get a second reading
		driveToEncoder(AUTO_DRIVE_SPEED, 2300);

		// Goal intermediate
		int sonar = readSonarMax(10);
		if (sonar == 0 || (sonar <= 90 && sonar >= 70)) {
			driveToGyro(80, TURN_LEFT);
			driveToEncoder(AUTO_DRIVE_SPEED, 2500);
			driveToGyro(115, !TURN_LEFT);

			// Turn to IR alignment
			valid = driveToIR(-AUTO_DRIVE_SPEED, true, false, IR_MID);

		// Goal ahead
		} else {
			valid = true;
		}
	}

	// Score if we are aligned
	if (valid) {
		valid = AutoScore();
	}

	// Kick if we scored
	if (valid) {
		AutoKickstand();
	}

	// Wiggle and flash if something went wrong
	if (!valid) {
		servoHookCapture();
		wait1Msec(500);
		servoHookRelease();
	}

	// Always return the lift to COLLECT, even if we failed
	setWaitLiftCmd(COLLECT);
}
