#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     motors,         sensorNone)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     liftTS,         sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftFrontMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftRearMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightRearMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     liftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     spinnerMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    goalHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    hopperTilt,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    highGoal,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    unusedS3C14,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    unusedS3C15,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    unusedS3C16,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickGame");
#include "../includes.h"

task main()
{
  initializeRobot();
  waitForStart();

  StartTask(Lift);
  waitLiftReady();

  // We need the hopper to score in rolling goals
  StartTask(Hopper);
  DriveSpinnerMotor(SPINNER_IN);

  // Make us drive safe
  setWaitLiftCmd(DRIVE);
  servoHookRelease();

  // Drive toward the goals and hope we hit one
  driveToEncoder(-AUTO_DRIVE_SPEED, 7750);
  servoHookCapture();

  // Score and wait for the lift to settle
  setLiftCmd(MED);
	waitLiftAboveRobot();
	hopperAutoDump();
	while(isLiftAboveRobot()) {
		abortTimeslice();
	}

  // Run back toward the parking zone
  driveToGyro(30, !TURN_LEFT);
  driveToEncoder(AUTO_DRIVE_SPEED, 8850);
  driveToGyro(120, !TURN_LEFT);

  // Release goal
  servoHookRelease();
  driveToEncoder(AUTO_DRIVE_SPEED, 1850);

  // Turn left and back into large goal
  driveToGyro(40, TURN_LEFT);
  driveToEncoder(-AUTO_DRIVE_SPEED, 3500);
  driveToGyro(80, TURN_LEFT);
  driveToEncoder(-AUTO_DRIVE_SPEED, 7000);

  //Set back to collect
  setLiftCmd(COLLECT);
}
